routes/web.php
<?php

use App\Http\Livewire\AccountTypes;
// use App\Models\AccountType;
use App\Models\Unit;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
    // return view('layouts.base');
});


Route::get('lang/{locale}', function ($locale) {
    App::setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::resource('brands', App\Http\Controllers\BrandController::class);


    Route::middleware('auth')->group(function() {
        // Route::livewire('/path-to-component', 'component');
        Route::view('accounts','accounts.home'); // ហៅ home.blade.php ពីក្នុង views/units
        // Route::view('account_types','livewire.account-types'); // ហៅ home.blade.php ពីក្នុង views/units
        // Route::view('account_types',AccountType::class); // ហៅ home.blade.php ពីក្នុង views/units
        Route::view('account-types','account_types.home'); // ហៅ home.blade.php ពីក្នុង views/units


        // Route::view('units','units.home'); // ហៅ home.blade.php ពីក្នុង views/units
        // Route::view('categories','livewire.categories'); // ហៅ home.blade.php ពីក្នុង Livewire
        // Route::view('categories','categories.home'); // ហៅ home.blade.php ធម្មតាមិនប្រើ Livewire
        Route::resource('categories', App\Http\Controllers\CategoryController::class);
        Route::resource('units', App\Http\Controllers\UnitController::class);


        Route::resource('products', App\Http\Controllers\ProductController::class);
        Route::resource('carts', App\Http\Controllers\CartController::class);



    });





});

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Unit extends Model
{
    use HasFactory;

    protected $fillable=[
        'business_id',
        'actual_name',
        'short_name',
        'allow_decimal',
        'created_by'
    ];



    public function users($id){
        return User::findOrFail($id);
        // return $this->hasMany(User::class,'created_by','id');
    }




    protected static function boot()
    {
        parent::boot();
        static::creating(function ($model) {
            $model->created_by = Auth::id();
            // $model->updated_by = Auth::id();
        });
        static::updating(function ($model) {
            // $model->updated_by = Auth::id();
        });
    }

}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Unit;
use Illuminate\Http\Request;

class UnitController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['units']=Unit::orderBy('id', 'DESC')->get();
        // $data['categories']=Category::orderBy('id', 'DESC')->get();
        // dd($data['categories']);

        return view('units.home',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         // return "Hello";
         $Parents=Unit::where('parent_id','=',0)->get();
         if( request()->ajax()){
		    return view('units.modal.add',compact('Parents'));
		}
        // return view('units.modal.add');
        return view('units.add',compact('Parents'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            $response = [
                'status' => false,
                'data' => [],
            ];


            $add = Unit::create([
                'business_id'  =>  1,
                'actual_name'   => $request->actual_name,
                'short_name'    => $request->short_name,
                'base_unit_id'     => $request->base_unit_id,
                'base_unit_multiplier'    => $request->base_unit_multiplier,
                'created_by'    => auth()->user()->id
            ]);

            // dd($add);

            if ($add) {
                $response = [
                    'status' => true,
                    //'data' => $add,
                    'dom' => view('categories.rows',['row' => $add])->render(),
                ];
            }



            if(request()->ajax()){
                return $response;
            }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        $Parents=Unit::where('base_unit_id','=',null)->get();
        // dd($unit);
        if( request()->ajax()){
		    return view('units.modal.edit',compact('unit','Parents'));
		}

        return view('units.edit',compact('unit','Parents'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Unit $unit)
    {
        $response = [
            'status' => false,
            'data' => [],
            // 'id' => $unit->id,
        ];
        $update = $unit->update([
            'business_id'  =>  1,
            'actual_name'          => $request->actual_name,
            'short_name'          => $request->short_name,
            'base_unit_id'          => $request->base_unit_id,
            // 'description'    => $request->description,
            'created_by'    => auth()->user()->id
        ]);

        if ($update) {
            $response = [
                'status' => true,
                'data' =>['id'=> $unit->id],
                // 'data' => $unit,
                'dom' => view('units.rows',['row' => $unit])->render(),

            ];

        }

        if(request()->ajax()){
            return $response;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $response = [
            'status' => false,
        ];
        $unit=Unit::findOrFail($id);


        // if ($unit->products->count() == 0) {
        //     $unit->delete();
        //     $response = [
        //         'status' => true,
        //     ];
        // }

        $unit->delete();
            $response = [
                'status' => true,
            ];

        if (request()->ajax()) {
            return $response;
        }

        return redirect()->route('units.index');
    }
}

resources/views/units/add.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container pt-3 px-4">
       {{-- @include('categories.modal.add') --}}
       <form action="{{ route('categories.store') }}" method="post">
        @csrf

        <div class="row">
            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    {{-- <label class="form-label" for="cat_name">Category Name</label> --}}
                    <input type="text" id="cat_name" class="form-control" name="name" placeholder="Category Name"/>

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    {{-- <label class="form-label" for="short_code">Short Code</label> --}}
                    <input type="text" id="short_code" class="form-control" name="short_code" placeholder="Short Code" />

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <label class="form-label" for="parent_id">Parent Category</label>
                    <select class="form-control" name="parent_id" id="parent_id">
                        <option value="0">Please Select</option>
                        @foreach ($Parents as $item)
                            <option value="{{$item->id}}">{{$item->name}}</option>
                        @endforeach

                    </select>
                    {{-- <input type="text" id="short_code" class="form-control" name="short_code" placeholder="Short Code" /> --}}

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <label class="form-label" for="description">{{ __('controls.description')}}</label>
                    <textarea id="description" class="form-control" cols="30"  rows="5" name="description"></textarea>

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <input type="submit" class="btn btn-success" value="Save">

                </div>
            </div>


        </div>
    </form>
    </div>

@endsection

resources/views/units/edit.blade.php
<div class="container pt-3 px-4">
    <form action="{{ route('brands.store') }}" method="post">
        @csrf

        <div class="row">
            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <input type="text" id="b_name" class="form-control" name="name" />
                    <label class="form-label" for="b_name">{{trans('controls.b_name')}}</label>
                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <textarea id="description" class="form-control" cols="30"  rows="5" name="description"></textarea>
                    {{-- {{!! Form::textarea($name, $value, [$options]) !!}} --}}
                    {{-- <input type="texteara" id="description" class="form-control" name="description" /> --}}

                    <label class="form-label" for="description">{{ __('controls.description')}}</label>
                </div>
            </div>
        </div>



    </form>
</div>

resources/views/units/home.blade.php
@extends('layouts.admin')

@push('css')

@endpush

@push('title','Manage Unit')

@section('content-header','Manage Unit')


@section('content')

     <!--Section: Sales Performance KPIs-->
     <section class="mb-4">
        <div class="card">
          <div class="card-header text-left py-3" style="height: 9vh;">
            <h5 class="mb-0 text-left">

                <strong>{{__('controls.Units')}}</strong>

                <span >
                    <a href="{{route('units.create')}}"
                    class="btn btn-primary btn-sm float-right"

                    data-toggle="modal-ajax"
                    {{-- data-toggle="modal" --}}
                    data-modal-size="modal-lg"
                    {{-- data-mdb-toggle="modal" --}}
                    {{-- data-target="#exampleModal" --}}
                    data-target="#openModal"
                    >
                    <i class="fas fa-plus-circle"></i> {{trans('controls.add')}}</a>
                </span>
            </h5>
          </div>


          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover text-nowrap" id="DataTableList">
                <thead>
                  <tr>
                    <th scope="col" style="width: 40px !important;">ID</th>
                    <th scope="col">{{__('controls.Unit Name')}}</th>
                    <th scope="col">{{__('controls.description')}}</th>
                    <th scope="col">{{__('controls.Parent Category')}}</th>
                    {{-- <th scope="col">{{__('controls.created by')}}</th> --}}
                    <th scope="col">{{__('controls.action')}}</th>
                  </tr>
                </thead>
                <tbody>

                    @foreach ($units as $row)
                        @include('units.rows')
                    @endforeach


                </tbody>
              </table>
            </div>
          </div>
        </div>
     </section>
      <!--Section: Sales Performance KPIs-->

{{-- @endif --}}


@endsection


@push('js')


<script>

    $(document).ready(function() {
        $('#DataTableList').DataTable({
            ordering:true,
            processing: false,
            // serverSide: true,
            "order": [[ 4, "asc" ]],
            language : $('html').attr('lang') != 'en' ? window.datatableI18n[$('html').attr('lang')] : null,
        });
    } );

        $(document).on('click',`[data-toggle="modal-ajax"]`,function(ev){
                    ev.preventDefault();
                    var url = $(this).attr('href');
                    var modalSize = $(this).data('modal-size');
                    var title = $(this).text();
                    // var target = $(this).data('mdb-target');
                    var target = $(this).data('target');


                    $.get(url).done((res)=>{
                        var $modal = $(target);
                        $modal.find('.modal-title').text(title);
                        $modal.find('.modal-dialog').addClass(modalSize);
                        $modal.find('.modal-body').html(res);


                        $modal.modal('show');

                        $modal.find('button#btn-submit').unbind().click(function(ev){
                            ev.preventDefault();

                            var $form = $modal.find('form');
                            var formData = new FormData($form[0]);
                            $.ajax({
                                url : $form.attr('action'),
                                method : 'post',
                                data : formData,
                                processData : false,
                                contentType : false,
                                success : (res)=>{
                                    if(res.status){

                                        Swal.fire({
                                            position: 'top-end',
                                            icon: 'success',
                                            title: '{{__('controls.Your data has been saved or updated!')}}',
                                            showConfirmButton: false,
                                            timer: 1500
                                        });


                                        if($(this).data('allow-close')){
                                            $modal.find(`[data-dismiss="modal"]`).click();
                                        }
                                        if ( url.match('edit')) {
                                            $('#DataTableList').find(`tr[data-id="${res.data.id}"]`).html($(res.dom).html());
                                        }else{
                                            $('#DataTableList').find('tbody').prepend(res.dom);
                                        }

                                        $form[0].reset();
                                    }

                                },
                            })

                        });
                        $modal.find(`[data-dismiss="modal"]`).click(function(ev){
                            ev.preventDefault();
                            $modal.modal('hide');
                            $modal.find('.modal-body').html("");

                        });


                    });

                });

</script>

{{-- Ajax Delete --}}
<script type="text/javascript">
    $(document).on('submit',`[data-toggle="formDelete"]`,function(ev){
        ev.preventDefault();
        $.ajax({
            url : $(this).attr('action'),
            method : 'post',
            data : new FormData(ev.target),
            processData : false,
            contentType : false,
            success : (res)=>{
                if(res.status){
                    Swal.fire(
                        '{{trans('controls.delete')}}!',
                        '{{trans('controls.Your file has been deleted.')}}',
                        'success'
                    );
                    $(this).parents("tr").remove();
                }else{
                    Swal.fire(
                        '{{trans('controls.delete')}}!',
                        '{{trans('controls.delete_message_can_not')}}',
                        'error'
                    )
                }
            }

        })
    });

    function deleteItem(id){
      Swal.fire({
        title: "{{trans('controls.Are you sure?')}}",
        text: "{{trans('controls.You will not be able to delete this!')}}",
        icon: 'warning',
        showCancelButton: true,

        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        cancelButtonText :"{{trans('controls.cancel')}}",
        confirmButtonText:  "{{trans('controls.Yes, delete it!')}}"
      }).then((result) => {
        if (result.value) {
          $('#frmDeleteItem-'+id).submit();

        }
      })
    }
</script>

@endpush

resources/views/units/rows.blade.php
<tr data-id="{{$row->id}}">
    <th scope="row" style="width: 40px !important;">{{$row->id}}</th>
    <td>{{$row->actual_name}}<br>
        <span class="text-success">
            {{-- <i class="fas fa-calculator me-1"></i> <span> {{ $row->products()->count() }} {{trans('controls.Products')}}</span> --}}
        </span>
    </td>
    <td>
        {{$row->short_name}}
    </td>
    <td>
        {{-- @if ($row->parent_id !=0)
            {{$row->CatParent($row->parent_id)->name}}
        @endif --}}

    </td>

    <td>
        <a class="btn btn-primary  edit_button sm" href="{{route('units.edit',$row->id)}}"
                data-toggle="modal-ajax"
                data-modal-size="modal-lg"
                data-target="#openModal"
        ><i class="fa fa-edit left"></i> {{ trans('controls.edit')}}</a>


        <a href="javascript:deleteItem({{ $row->id }})"​​ class="btn btn-danger delete_button sm"><i class="fa fa-trash-alt left"></i> {{ trans('controls.delete')}}</a>


        <form data-toggle="formDelete"  id="frmDeleteItem-{{ $row->id }}" style="display: none" action="{{ route('units.destroy',$row->id) }}" role="form" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
        </form>

    </td>
</tr>