routes/web.php
<?php

use App\Http\Livewire\AccountTypes;
// use App\Models\AccountType;
use App\Models\Unit;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
    // return view('layouts.base');
});


Route::get('lang/{locale}', function ($locale) {
    App::setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::resource('brands', App\Http\Controllers\BrandController::class);


    Route::middleware('auth')->group(function() {
        // Route::livewire('/path-to-component', 'component');
        Route::view('accounts','accounts.home'); // ហៅ home.blade.php ពីក្នុង views/units
        // Route::view('account_types','livewire.account-types'); // ហៅ home.blade.php ពីក្នុង views/units
        // Route::view('account_types',AccountType::class); // ហៅ home.blade.php ពីក្នុង views/units
        Route::view('account-types','account_types.home'); // ហៅ home.blade.php ពីក្នុង views/units


        // Route::view('units','units.home'); // ហៅ home.blade.php ពីក្នុង views/units
        // Route::view('categories','livewire.categories'); // ហៅ home.blade.php ពីក្នុង Livewire
        // Route::view('categories','categories.home'); // ហៅ home.blade.php ធម្មតាមិនប្រើ Livewire
        Route::resource('categories', App\Http\Controllers\CategoryController::class);
        Route::resource('units', App\Http\Controllers\UnitController::class);


        Route::resource('products', App\Http\Controllers\ProductController::class);
        Route::resource('carts', App\Http\Controllers\CartController::class);



    });





});

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Unit extends Model
{
    use HasFactory;

    protected $fillable=[
        'business_id',
        'actual_name',
        'short_name',
        'allow_decimal',
        'created_by'
    ];



    public function users($id){
        return User::findOrFail($id);
        // return $this->hasMany(User::class,'created_by','id');
    }




    protected static function boot()
    {
        parent::boot();
        static::creating(function ($model) {
            $model->created_by = Auth::id();
            // $model->updated_by = Auth::id();
        });
        static::updating(function ($model) {
            // $model->updated_by = Auth::id();
        });
    }

}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Unit;
use Illuminate\Http\Request;

class UnitController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['units']=Unit::orderBy('id', 'DESC')->get();
        // $data['categories']=Category::orderBy('id', 'DESC')->get();
        // dd($data['categories']);

        return view('units.home',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         // return "Hello";
         $Parents=Unit::where('parent_id','=',0)->get();
         if( request()->ajax()){
		    return view('units.modal.add',compact('Parents'));
		}
        // return view('units.modal.add');
        return view('units.add',compact('Parents'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            $response = [
                'status' => false,
                'data' => [],
            ];


            $add = Unit::create([
                'business_id'  =>  1,
                'actual_name'   => $request->actual_name,
                'short_name'    => $request->short_name,
                'base_unit_id'     => $request->base_unit_id,
                'base_unit_multiplier'    => $request->base_unit_multiplier,
                'created_by'    => auth()->user()->id
            ]);

            // dd($add);

            if ($add) {
                $response = [
                    'status' => true,
                    //'data' => $add,
                    'dom' => view('categories.rows',['row' => $add])->render(),
                ];
            }



            if(request()->ajax()){
                return $response;
            }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        $Parents=Unit::where('base_unit_id','=',null)->get();
        // dd($unit);
        if( request()->ajax()){
		    return view('units.modal.edit',compact('unit','Parents'));
		}

        return view('units.edit',compact('unit','Parents'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Unit $unit)
    {
        $response = [
            'status' => false,
            'data' => [],
            // 'id' => $unit->id,
        ];
        $update = $unit->update([
            'business_id'  =>  1,
            'actual_name'          => $request->actual_name,
            'short_name'          => $request->short_name,
            'base_unit_id'          => $request->base_unit_id,
            // 'description'    => $request->description,
            'created_by'    => auth()->user()->id
        ]);

        if ($update) {
            $response = [
                'status' => true,
                'data' =>['id'=> $unit->id],
                // 'data' => $unit,
                'dom' => view('units.rows',['row' => $unit])->render(),

            ];

        }

        if(request()->ajax()){
            return $response;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $response = [
            'status' => false,
        ];
        $unit=Unit::findOrFail($id);


        // if ($unit->products->count() == 0) {
        //     $unit->delete();
        //     $response = [
        //         'status' => true,
        //     ];
        // }

        $unit->delete();
            $response = [
                'status' => true,
            ];

        if (request()->ajax()) {
            return $response;
        }

        return redirect()->route('units.index');
    }
}

resources/views/units/modal/add.blade.php
<div class="container pt-3 px-4">
    <form class="form-horizontal" action="{{ route('categories.store') }}" method="post">
        @csrf

        <div class="row">

            <div class="form-group row">
                <label for="inputEmail3" class="col-md-3 col-form-label">Email</label>
                <div class="col-md-9">
                  <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
            </div>




            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <label class="form-label" for="cat_name">Category Name</label>
                    <input type="text" id="cat_name" class="form-control" name="name" placeholder="{{trans('controls.Category Name')}}"/>

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    {{-- <label class="form-label" for="short_code">Short Code</label> --}}
                    <input type="text" id="short_code" class="form-control" name="short_code" placeholder="Short Code" />

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <label class="form-label" for="parent_id">{{trans('controls.Parent Category')}}</label>
                    <select class="form-control" name="parent_id" id="parent_id">
                        <option value="0">Please Select</option>
                        @foreach ($Parents as $item)
                            <option value="{{$item->id}}">{{$item->name}}</option>
                        @endforeach

                    </select>
                    {{-- <input type="text" id="short_code" class="form-control" name="short_code" placeholder="Short Code" /> --}}

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <label class="form-label" for="description">{{ __('controls.description')}}</label>
                    <textarea id="description" class="form-control" cols="30"  rows="5" name="description"></textarea>

                </div>
            </div>
        </div>
    </form>
</div>

resources/views/units/modal/edit.blade.php
<div class="container pt-3 px-4">
    <form action="{{ route('units.update',$unit) }}" method="post">
        @csrf
        {{ method_field('PUT') }}
        <div class="row">
            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    {{-- <label class="form-label" for="cat_name">Category Name</label> --}}
                    <input type="text" id="actual_name" class="form-control" name="actual_name" value="{{$unit->actual_name}}" placeholder="{{trans('controls.Category Name')}}"/>

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    {{-- <label class="form-label" for="short_code">Short Code</label> --}}
                    <input type="text" id="short_name" class="form-control" name="short_name" value="{{$unit->short_name}}" placeholder="Short Code" />

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <label class="form-label" for="base_unit_id">{{trans('Base Unit')}}</label>
                    <select class="form-control" name="base_unit_id" id="base_unit_id">
                        <option value="null">Please Select</option>
                        @foreach ($Parents as $item)
                            <option {{$item->id==$unit->base_unit_id?'selected':''}} value="{{$item->id}}">{{$item->actual_name}}</option>
                        @endforeach
                    </select>

                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <label class="form-label" for="description">{{ __('controls.description')}}</label>
                    <textarea id="description" class="form-control" cols="30"  rows="5" name="description">{{$unit->short_name}}</textarea>

                </div>
            </div>
        </div>



    </form>
</div>